//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8C TS KC 9H 4S 7D 2S 5D 3S AC
        ///5C AD 5D AC 9C 7C 5H 8D TD KS
        ///3H 7H 6S KC JS QH TD JC 2D 8S
        ///TH 8H 5C QS TC 9H 4D JC KS JS
        ///7C 5H KC QH JD AS KH 4C AD 4S
        ///5H KS 9C 7D 9H 8D 3S 5D 5C AH
        ///6H 4H 5C 3H 2H 3S QH 5S 6S AS
        ///TD 8C 4H 7C TC KC 4C 3H 7S KS
        ///7C 9C 6D KD 3H 4C QS QC AC KH
        ///JC 6S 5H 2H 2D KD 9D 7C AS JS
        ///AD QH TH 9D 8H TS 6D 3S AS AC
        ///2H 4S 5C 5S TC KC JD 6C TS 3C
        ///QD AS 6H JS 2C 3D 9H KC 4H 8S
        ///KD 8S 9S 7C 2S 3S 6D 6S 4H KC
        ///3C 8C 2D 7D 4D 9S 4S QH 4H JD
        ///8C KC 7S TC 2D TS 8H QD AC 5C
        ///3D KH QD 6C 6S A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poker {
            get {
                return ResourceManager.GetString("poker", resourceCulture);
            }
        }
    }
}
